### ISSUE TITLE
Use .equals("Red") instead of == "Red"

### ISSUE THREAD

**Issue by rjbohinski** [2729StormRobotics/StormRobotics2020#39]
https://github.com/2729StormRobotics/StormRobotics2020/blob/58aca8f42bfbd73810ecd9a0b202380c8f17564a/src/main/java/frc/robot/subsystems/ControlPanel.java#L83-L91

Explanation: https://sonarcloud.io/organizations/storm-robotics-2729-github/rules?open=java%3AS4973&rule_key=java%3AS4973

**Comment by hrose967** [comment]
-
