### ISSUE TITLE
Cast one of the operands of this division operation to a "double"

### ISSUE THREAD

**Issue by rjbohinski** [2729StormRobotics/StormRobotics2020#61]
https://github.com/2729StormRobotics/StormRobotics2020/blob/2ff813a9f863b0d4c97a8c3ea607076c4fcf04c1/src/main/java/frc/robot/Constants.java#L33-L35

https://github.com/2729StormRobotics/StormRobotics2020/blob/2ff813a9f863b0d4c97a8c3ea607076c4fcf04c1/src/main/java/frc/robot/Constants.java#L171-L172

Explanation: https://sonarcloud.io/organizations/storm-robotics-2729-github/rules?open=java%3AS2184&rule_key=java%3AS2184

**Comment by PKuppili** [comment]
A pull request to Dev fixed this issue. Thanks for bringing it up!
